image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
  - name: Connect to MySQL
    command: mysql
  - name: Create Database
    command: CREATE DATABASE products;

ports:
  - port: 4000
    visibility: public
    onOpen: open-browser